model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo   # The `openai/` prefix will call openai.chat.completions.create
      api_key: os.environ/OPENAI_API_KEY